### PR TITLE
feat: added hono/jsx-dom with vite example

### LINKED ISSUE #197: Add example to use hono/jsx-dom
Many people in the community are unsure how to use [Client Componet](https://hono.dev/docs/guides/jsx-dom) with `hono`, basically how to set it up and start using it in dev/prod.

I can create a PR for this using `vite`.

### PR DESCRIPTION
**Pull request by MathurAditya724**
Closes #197

### CODE REVIEW

**Review by yusukebe — COMMENTED** [review]
Can you add this template to the `workspaces` in `package.json` on the top?:

```diff
diff --git a/package.json b/package.json
index dfb17d9..f38364f 100644
--- a/package.json
+++ b/package.json
@@ -11,7 +11,8 @@
     "serve-static",
     "bun",
     "pages-stack",
-    "nextjs-stack"
+    "nextjs-stack",
+    "hono-vite-jsx"
   ],
   "license": "MIT",
   "packageManager": "yarn@3.2.1"
```

**Comment by yusukebe** [comment]
Hi @MathurAditya724 

This is simple and good. I've left a comment.

**Comment by MathurAditya724** [comment]
Done

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@MathurAditya724 

Thank you! Let's gooo!

**Pull request merged**
